#!/sbin/busybox sh

cd /sbin

for i in $(./busybox --list)
do
	./busybox ln -s busybox $i
done

cd /

mount -t proc proc /proc
mount -t sysfs sysfs /sys

mkdir -p /dev/block

mknod /dev/block/mmcblk0p20 b 179 20
mknod /dev/block/loop0 b 7 0

mount -t ext4 /dev/block/mmcblk0p20 /system

out() {
	umount -f /system

	chmod 755 /init
	chmod 644 /*.qcom
	chmod 644 /*.rc
	chmod 644 /*.prop
	chmod -R 755 /lib

	exec /init
}

mv -f /res/aosp44/* /

[ -d /system/app/Synapse.apk ] || mv -f /res/synapse/Synapse.apk /system/app/ && chmod 644 /system/app/Synapse.apk

out
